version: '3.9'

services:
  web:
    build:
      context: .
    container_name: url_shortener_api
    entrypoint: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn url_shortener.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_server
    ports:
      - "8001:80" # Serve Nginx on port 8001
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media

volumes:
  static_volume:
  media_volume:
