# Generated by Django 5.1.7 on 2025-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
