# Generated by Django 5.1.1 on 2025-05-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shorten", "0004_alter_url_long_url_alter_url_short_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
