# Generated by Django 5.1.1 on 2025-05-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shorten", "0005_url_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clickevent",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="referrer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clickevent",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
