# Generated by Django 5.1.1 on 2025-05-30 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shorten", "0006_clickevent_city_clickevent_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="short_code",
            field=models.TextField(blank=True, db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["url", "clicked_at"], name="tb_url_anal_url_id_3fec1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["ip_address"], name="tb_url_anal_ip_addr_9f0887_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["country"], name="tb_url_anal_country_879252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["user", "short_code"], name="tb_urls_user_id_f50ea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["created_at"], name="tb_urls_created_2b3baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["clicks"], name="tb_urls_clicks_9b4a78_idx"),
        ),
    ]
